Repository saleshandy/design-system, pull requests merged in 2022-12, with the labels that each got.

#28 Progress-Bar Component
  src/assets/scss/components/_progress-bar.scss
  src/assets/scss/design-system.scss
  src/components/progress-bar/helper.ts
  src/components/progress-bar/index.tsx
  src/components/progress-bar/progress-bar.tsx
  src/components/progress-bar/types.ts
  src/stories/progress-bar.stories.tsx
Labels: ready to merge

#30 SH-5933 ADD(Component): progress-bar
  src/index.ts
Labels: ready to merge

#29 chore: upgraded the storybook dependencies
  package-lock.json
  package.json
Labels: ready to merge, configurations

#37 feat: added new icons and updated the story definition
  src/assets/fonts/SalesHandy.eot
  src/assets/fonts/SalesHandy.svg
  src/assets/fonts/SalesHandy.ttf
  src/assets/fonts/SalesHandy.woff
  src/assets/fonts/_fontStyles.scss
  src/assets/fonts/_fontVariables.scss
  src/stories/icon.stories.tsx
  src/stories/scss/index.stories.scss
Labels: enhancement, ready to merge

#38 feat(SH-4359): added button component
  .storybook/main.js
  package-lock.json
  package.json
  src/assets/scss/components/_button.scss
  src/components/button/button.tsx
  src/components/button/types.ts
  src/stories/button.stories.tsx
  src/stories/scss/index.stories.scss
Labels: enhancement, ready to merge

#39 feat(SH-5011): added toaster component
  .storybook/main.js
  package-lock.json
  package.json
  src/assets/scss/components/_toast.scss
  src/assets/scss/design-system.scss
  src/components/toaster/index.ts
  src/components/toaster/toast-helper.ts
  src/components/toaster/toast-manager.tsx
  src/components/toaster/toast.tsx
  src/components/toaster/types.ts
  src/index.ts
  src/stories/scss/index.stories.scss
  src/stories/toaster.stories.tsx
  src/utils/constants.ts
  tsconfig.json
Labels: enhancement, ready to review

#41 fix: updated duration prop for toaster
  src/components/button/button.tsx
  src/components/toaster/toast.tsx
  src/stories/toaster.stories.tsx
Labels: documentation, enhancement

#42 chore: fixed dependency issue
  package-lock.json
Labels: configurations

#43 chore: added new github workflow to run check for storybook build
  .github/workflows/storybook-check.yml
Labels: configurations

#44 feat(SH-4358): added avatar component
  package-lock.json
  package.json
  src/assets/scss/components/_avatar.scss
  src/assets/scss/design-system.scss
  src/components/avatar/avatar.spec.tsx
  src/components/avatar/avatar.tsx
  src/components/avatar/index.ts
  src/components/avatar/types.ts
  src/index.ts
  src/stories/avatar.stories.tsx
  src/stories/button.stories.tsx
  src/utils/constants.ts
Labels: enhancement, ready to merge

#45 fix: component export error
  src/components/toaster/index.ts
  src/index.ts
  src/stories/toaster.stories.tsx
Labels: bug, ready to merge
